# Generated by Django 3.1.4 on 2023-08-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230723_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
