# Generated by Django 3.1.4 on 2023-08-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20230823_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field= models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
